server:
  port: 8080
spring:
  application:
    name: GameShop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.237.233:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chen
    password: 123456
  redis:
    host: 124.221.237.233
    database: 0
  servlet:
    multipart:
      max-file-size: 100MB
minio:
  endpoint: http://124.221.237.233:9000
  accessKey: chen
  secretKey: 123456789
mybatis:
  mapper-locations: classpath:mapperXMl/*.xml
  type-aliases-package: com.example.newgameshop.entity
